name: ticketing_system
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.1.12
  http: ^1.1.0
  flutter_material_color_picker: ^1.2.0
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  intl: ^0.18.1
  provider: ^6.0.5
  dynamic_color: ^1.6.6
  qr_flutter: ^4.1.0
  sunmi_printer_plus: ^2.1.01
  shared_preferences: ^2.0.8
  babstrap_settings_screen: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/images/
